source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'vilcore_Example', :exclusive => true do
  pod "vilcore", :path => "../"
end

target 'vilcore_Tests', :exclusive => true do
  pod "vilcore", :path => "../"

  
end
